services:
    comerito_report.loader.reports_data_loader:
        class: Comerito\Bundle\ReportBundle\Loader\ReportsDataLoader
        arguments:
            - '@doctrine'
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: comerito_report_plugin }

